"use client";
import React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, ArrowRight, Building2, CalendarDays, CheckCircle2, Copy, MapPin, MessageSquare, Ruler, Share2, ShieldCheck } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

type Project={id:string;slug:string;title:string;summary:string;category:string;location:string;budgetRange:string;areaSqFt:number;timeline:string;status:string;coverImage:string;gallery:string[];highlights:string[];scope:string[];deliverables:string[];featured:boolean;views:number};
export default function ProjectDetailPage(){
 const {slug}=useParams<{slug:string}>(); const [p,setP]=React.useState<Project|null>(null); const [loading,setLoading]=React.useState(true); const [open,setOpen]=React.useState(false); const [sent,setSent]=React.useState(false); const [error,setError]=React.useState("");
 React.useEffect(()=>{if(slug) fetch(`/api/public-projects?slug=${encodeURIComponent(slug)}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setP).finally(()=>setLoading(false));},[slug]);
 const share=async()=>{if(!p)return; const url=window.location.href; try{if(navigator.share) await navigator.share({title:p.title,text:p.summary,url}); else {await navigator.clipboard.writeText(url); alert("Project link copied");}}catch{}};
 if(loading)return <div className="min-h-screen bg-slate-50"><Header/><div className="mx-auto max-w-7xl px-4 py-20"><div className="h-96 animate-pulse rounded-3xl bg-slate-200"/></div></div>;
 if(!p)return <div className="min-h-screen bg-slate-50"><Header/><main className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="text-3xl font-black">Project not found</h1><Link href="/projects" className="mt-6 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Back to projects</Link></main><Footer/></div>;
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError("");const data=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/project-inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,projectId:p.id})});const d=await r.json();if(!r.ok){setError(d.error||"Could not submit");return;}setSent(true);};
 return <div className="min-h-screen bg-[#f5f7fa] text-slate-900"><Header/><main>
  <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-8 md:px-8"><Link href="/projects" className="inline-flex items-center gap-2 text-xs font-bold text-slate-300 hover:text-white"><ArrowLeft className="h-4 w-4"/> All projects</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-orange-500 px-3 py-1 text-[10px] font-black uppercase">{p.category}</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[10px] font-bold">{p.status}</span></div><h1 className="mt-5 max-w-4xl text-4xl font-black tracking-tight md:text-6xl">{p.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-slate-300">{p.summary}</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><button onClick={share} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-sm font-bold hover:bg-white/10"><Share2 className="h-4 w-4"/> Share project</button><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-black text-white hover:bg-orange-400">I want this project <ArrowRight className="h-4 w-4"/></button></div></div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-8 md:px-8"><div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><div>
   <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{p.coverImage?<img src={p.coverImage} alt={p.title} className="h-[420px] w-full object-cover"/>:<div className="flex h-[420px] items-center justify-center bg-gradient-to-br from-slate-800 to-slate-950"><Building2 className="h-20 w-20 text-white/20"/></div>}</div>
   {p.gallery?.length>0&&<div className="mt-4 grid grid-cols-3 gap-3">{p.gallery.slice(0,6).map((img,i)=><img key={i} src={img} alt={`${p.title} ${i+1}`} className="h-28 w-full rounded-2xl object-cover"/>)}</div>}
   <div className="mt-8 grid gap-4 md:grid-cols-2">{[[MapPin,"Location",p.location||"Private / on discussion"],[Ruler,"Project scale",p.areaSqFt?`${p.areaSqFt.toLocaleString("en-IN")} sq.ft`:"To be confirmed"],[CalendarDays,"Timeline",p.timeline||"To be discussed"],[Copy,"Commercial",p.budgetRange||"Discuss after enquiry"]].map(([Icon,label,value]:any)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><Icon className="h-5 w-5 text-orange-600"/><p className="mt-3 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p></div>)}</div>
   {([["Project highlights",p.highlights],["Scope of work",p.scope],["Expected deliverables",p.deliverables]] as [string,string[]][]).map(([title,items])=>items?.length?<section key={title} className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 md:p-8"><h2 className="text-xl font-black">{title}</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{items.map((x,i)=><div key={i} className="flex gap-3 rounded-2xl bg-slate-50 p-4 text-sm text-slate-700"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600"/>{x}</div>)}</div></section>:null)}
  </div><aside className="lg:sticky lg:top-24 lg:h-fit"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-orange-50 p-3"><MessageSquare className="h-5 w-5 text-orange-600"/></div><div><h2 className="font-black">Interested in this project?</h2><p className="text-xs text-slate-500">Tell us who you are. We will discuss the detailed brief privately.</p></div></div><button onClick={()=>setOpen(true)} className="mt-6 w-full rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white hover:bg-orange-600">I want this project</button><div className="mt-5 flex gap-3 rounded-2xl bg-emerald-50 p-4"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-600"/><p className="text-xs leading-5 text-emerald-900">Public information is intentionally limited. Personal client details and sensitive commercial terms are not shown here.</p></div></div></aside></div></section>
 </main><Footer/>
 {open&&<div className="fixed inset-0 z-[300] flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm" onClick={()=>setOpen(false)}><div onClick={e=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl md:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-orange-600">Project enquiry</p><h2 className="mt-1 text-2xl font-black">I want this project</h2><p className="mt-1 text-sm text-slate-500">{p.title}</p></div><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100">×</button></div>{sent?<div className="py-12 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100"><CheckCircle2 className="h-7 w-7 text-emerald-600"/></div><h3 className="mt-4 text-xl font-black">Enquiry received</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">Our team has your project selection and contact details. We can now follow up with the private brief.</p><button onClick={()=>setOpen(false)} className="mt-6 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Done</button></div>:<form onSubmit={submit} className="mt-6 space-y-4"><div className="grid gap-4 md:grid-cols-2"><input name="name" required placeholder="Your name *" className="rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-orange-500"/><input name="company" placeholder="Company / firm" className="rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-orange-500"/></div><div className="grid gap-4 md:grid-cols-2"><input name="email" type="email" required placeholder="Work email *" className="rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-orange-500"/><input name="phone" required placeholder="Phone / WhatsApp *" className="rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-orange-500"/></div><textarea name="message" rows={5} placeholder="Tell us about your capability, location, timeline or questions..." className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-orange-500"/>{error&&<p className="rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</p>}<button className="w-full rounded-xl bg-orange-500 px-5 py-3.5 text-sm font-black text-white hover:bg-orange-400">Submit project interest</button><p className="text-center text-[10px] leading-4 text-slate-400">By submitting, you agree that Civil At Hand may contact you about this specific opportunity.</p></form>}</div></div>}
 </div>
}
