"use client";

import { useEffect, useMemo, useState } from "react";
import { Bookmark, Check, ClipboardList, MessageSquareText, Pin, Plus, Search, X } from "lucide-react";
import { auth } from "@/lib/firebase";
import ChannelMessageManager from "@/components/admin/ChannelMessageManager";

async function token() { const user=auth.currentUser; return user ? user.getIdToken() : ""; }
async function api(groupId:string, body:Record<string,unknown>) { const t=await token(); const r=await fetch("/api/community/features",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({groupId,...body})}); const d=await r.json().catch(()=>({})); if(!r.ok||!d.success)throw new Error(d.error||"Chat Pro action failed."); return d; }

type Props={groupId:string; messages?:Array<{id:string;text:string;username:string;createdAt:string}>; onClose?:()=>void};
export default function CommunityChatPro({groupId,messages=[],onClose}:Props){
 const [open,setOpen]=useState(false),[tab,setTab]=useState<"saved"|"pins"|"polls"|"tasks">("saved"),[data,setData]=useState<any>({saved:[],pins:[],polls:[],tasks:[]}),[error,setError]=useState(""),[question,setQuestion]=useState(""),[options,setOptions]=useState(["",""]),[task,setTask]=useState("");
 const load=async()=>{try{const t=await token();const r=await fetch(`/api/community/features?groupId=${encodeURIComponent(groupId)}`,{cache:"no-store",headers:{Authorization:`Bearer ${t}`}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||"Unable to load Chat Pro.");setData(d);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load Chat Pro.")}};
 useEffect(()=>{if(open)void load()},[open,groupId]);
 const msgMap=useMemo(()=>new Map(messages.map(m=>[m.id,m])),[messages]);
 const save=(id:string)=>api(groupId,{action:data.saved.some((x:any)=>x.messageId===id)?"unsave":"save",messageId:id}).then(load).catch(e=>setError(e.message));
 if(!open)return <><ChannelMessageManager channelId={groupId} onlyChannelAdmins /><button type="button" onClick={()=>setOpen(true)} aria-label="Open Chat Pro" className="fixed bottom-5 right-5 z-50 inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 text-xs font-black text-white shadow-xl hover:bg-slate-800"><MessageSquareText className="h-4 w-4"/> Chat Pro</button></>;
 return <aside className="fixed inset-x-3 bottom-3 z-50 max-h-[78vh] overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl sm:left-auto sm:right-5 sm:w-[420px]">
  <header className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><b className="text-sm font-black text-slate-950">Community Chat Pro</b><p className="text-[10px] text-slate-400">Saved messages, pins, polls and tasks</p></div><button type="button" onClick={()=>{setOpen(false);onClose?.()}} aria-label="Close Chat Pro" className="rounded-xl p-2 text-slate-500 hover:bg-slate-100"><X className="h-4 w-4"/></button></header>
  <nav className="grid grid-cols-4 gap-1 border-b border-slate-100 p-2">{([["saved",Bookmark,"Saved"],["pins",Pin,"Pins"],["polls",MessageSquareText,"Polls"],["tasks",ClipboardList,"Tasks"]] as const).map(([id,Icon,label])=><button key={id} type="button" onClick={()=>setTab(id)} className={`rounded-xl px-2 py-2 text-[10px] font-black ${tab===id?"bg-slate-950 text-white":"text-slate-500 hover:bg-slate-50"}`}><Icon className="mx-auto mb-1 h-4 w-4"/>{label}</button>)}</nav>
  <div className="max-h-[58vh] overflow-y-auto p-4">
   {error&&<div className="mb-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-[10px] font-bold text-rose-700">{error}</div>}
   {tab==="saved"&&<div className="space-y-2">{data.saved.length?data.saved.map((x:any)=><button key={x.id} type="button" onClick={()=>msgMap.has(x.messageId)&&save(x.messageId)} className="w-full rounded-2xl border border-slate-200 p-3 text-left hover:bg-slate-50"><b className="text-[10px] text-slate-400">Saved</b><p className="mt-1 text-xs text-slate-700">{msgMap.get(x.messageId)?.text||"Saved message"}</p></button>):<Empty text="No saved messages yet."/>}</div>}
   {tab==="pins"&&<div className="space-y-2">{data.pins.length?data.pins.map((x:any)=><div key={x.id} className="rounded-2xl border border-slate-200 p-3"><b className="text-[10px] text-slate-400">Pinned</b><p className="mt-1 text-xs text-slate-700">{msgMap.get(x.messageId)?.text||"Pinned message"}</p></div>):<Empty text="No pinned messages yet."/>}</div>}
   {tab==="polls"&&<div className="space-y-4"><div className="rounded-2xl border border-slate-200 p-3"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a poll question" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-xs outline-none"/>{options.map((v,i)=><input key={i} value={v} onChange={e=>setOptions(a=>a.map((x,j)=>j===i?e.target.value:x))} placeholder={`Option ${i+1}`} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2 text-xs outline-none"/>)}<div className="mt-2 flex gap-2"><button type="button" onClick={()=>setOptions(a=>a.length<8?[...a,""]:a)} className="rounded-xl border px-3 py-2 text-[10px] font-black"><Plus className="mr-1 inline h-3 w-3"/>Option</button><button type="button" onClick={()=>api(groupId,{action:"poll_create",question,options}).then(()=>{setQuestion("");setOptions(["",""]);return load()}).catch(e=>setError(e.message))} className="rounded-xl bg-slate-950 px-3 py-2 text-[10px] font-black text-white">Create poll</button></div></div>{data.polls.map((p:any)=><div key={p.id} className="rounded-2xl border border-slate-200 p-3"><b className="text-xs">{p.question}</b>{p.options.map((o:string,i:number)=><button key={i} type="button" onClick={()=>api(groupId,{action:"poll_vote",pollId:p.id,optionIndex:i}).then(load).catch(e=>setError(e.message))} className="mt-2 flex w-full items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-left text-xs hover:bg-slate-100"><span>{o}</span><span>{Number(p.votes?.[i]||0)}</span></button>)}</div>)}</div>}
   {tab==="tasks"&&<div><div className="mb-3 flex gap-2"><input value={task} onChange={e=>setTask(e.target.value)} placeholder="New task" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2 text-xs outline-none"/><button type="button" onClick={()=>api(groupId,{action:"task_create",title:task}).then(()=>{setTask("");return load()}).catch(e=>setError(e.message))} className="rounded-xl bg-slate-950 px-3 py-2 text-[10px] font-black text-white">Add</button></div>{data.tasks.map((x:any)=><div key={x.id} className="mb-2 flex items-center gap-2 rounded-2xl border border-slate-200 p-3"><button type="button" onClick={()=>api(groupId,{action:"task_update",taskId:x.id,done:!x.done}).then(load).catch(e=>setError(e.message))} className={`grid h-6 w-6 place-items-center rounded-lg border ${x.done?"bg-emerald-50 text-emerald-600":"bg-white text-slate-300"}`}><Check className="h-3.5 w-3.5"/></button><span className={`text-xs font-bold ${x.done?"text-slate-400 line-through":"text-slate-700"}`}>{x.title}</span></div>)}</div>}
  </div>
 </aside>;
}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-xs font-bold text-slate-400"><Search className="mx-auto mb-2 h-5 w-5"/>{text}</div>}
