"use client";
import React, { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Eye, EyeOff, Plus, Save, Trash2, ExternalLink } from "lucide-react";
import { notifyAdmin } from "./AdminToast";
type Item={id:string;label:string;href:string;help?:string;icon?:string;visible:boolean;external?:boolean};
const blank=():Item=>({id:`nav-${Date.now()}`,label:"New link",href:"/",help:"",icon:"Globe2",visible:true,external:false});
export function WebsiteNavigationPanel(){const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/admin/site-navigation",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed");setItems(d.items||[]);}catch(e){notifyAdmin(e instanceof Error?e.message:"Could not load navigation.","error")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const update=(id:string,key:keyof Item,value:unknown)=>setItems(v=>v.map(i=>i.id===id?{...i,[key]:value}:i));
 const move=(index:number,delta:number)=>{const next=index+delta;if(next<0||next>=items.length)return;const a=[...items];[a[index],a[next]]=[a[next],a[index]];setItems(a)};
 const remove=(id:string)=>{if(!confirm("Remove this item from the public navigation?"))return;setItems(v=>v.filter(i=>i.id!==id))};
 const save=async()=>{setSaving(true);try{const clean=items.filter(i=>i.label.trim()&&i.href.trim());const r=await fetch("/api/admin/site-navigation",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:clean})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed");setItems(d.items||clean);notifyAdmin("Public navigation saved.","success")}catch(e){notifyAdmin(e instanceof Error?e.message:"Save failed","error")}finally{setSaving(false)}};
 return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-extrabold text-slate-950">Website Navigation</h3><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-500">Control the public header menu without editing code. Changes apply to desktop and mobile navigation after publish.</p></div><div className="flex gap-2"><button type="button" onClick={()=>setItems(v=>[...v,blank()])} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700"><Plus className="h-3.5 w-3.5"/> Add option</button><button type="button" onClick={save} disabled={saving||loading} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-3 py-2 text-xs font-bold text-white disabled:opacity-60"><Save className="h-3.5 w-3.5"/>{saving?"Saving…":"Save navigation"}</button></div></div>
 {loading?<div className="rounded-2xl border border-slate-200 p-6 text-sm text-slate-500">Loading navigation…</div>:<div className="space-y-3">{items.map((item,index)=><div key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 lg:grid-cols-[auto_1.3fr_1fr_1.3fr_auto] lg:items-end"><div className="flex gap-2 lg:pb-1"><button type="button" title="Move up" onClick={()=>move(index,-1)} className="rounded-lg border border-slate-200 p-2 text-slate-500 disabled:opacity-30" disabled={index===0}><ArrowUp className="h-4 w-4"/></button><button type="button" title="Move down" onClick={()=>move(index,1)} className="rounded-lg border border-slate-200 p-2 text-slate-500 disabled:opacity-30" disabled={index===items.length-1}><ArrowDown className="h-4 w-4"/></button></div><label><span className="mb-1 block text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Label</span><input value={item.label} onChange={e=>update(item.id,"label",e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label><span className="mb-1 block text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Link</span><input value={item.href} onChange={e=>update(item.id,"href",e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label><span className="mb-1 block text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Helper text</span><input value={item.help||""} onChange={e=>update(item.id,"help",e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><div className="flex items-center gap-2 lg:pb-1"><button type="button" onClick={()=>update(item.id,"visible",!item.visible)} className={`inline-flex items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-bold ${item.visible?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{item.visible?<Eye className="h-3.5 w-3.5"/>:<EyeOff className="h-3.5 w-3.5"/>}{item.visible?"Visible":"Hidden"}</button><button type="button" onClick={()=>update(item.id,"external",!item.external)} className={`rounded-xl px-3 py-2 text-xs font-bold ${item.external?"bg-blue-50 text-blue-700":"bg-slate-100 text-slate-500"}`}>{item.external?<ExternalLink className="inline h-3.5 w-3.5 mr-1"/>:null}External</button><button type="button" onClick={()=>remove(item.id)} className="rounded-xl border border-rose-200 p-2 text-rose-600"><Trash2 className="h-4 w-4"/></button></div></div></div>)}</div>}
 </div>}
