import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { getSitePage, mergePageFallback } from "@/lib/siteContent";
import { digitalCapabilities } from "@/data/brandExperience";

export const metadata: Metadata = { title: "Digital Engineering", description: "NS Construction digital engineering capabilities across BIM, CAD, quantity workflows, GIS and project information." };

export default async function TechnologyPage() {
  const pageContent = mergePageFallback({ slug: "technology", path: "/technology", pageType: "existing", status: "published", title: "Digital Engineering", description: "Digital engineering capabilities across BIM, CAD, GIS and project information.", heroTitle: "Digital Engineering", heroDescription: "Digital engineering capabilities across BIM, CAD, GIS and project information." }, await getSitePage("technology"));

  return <div className="min-h-screen bg-white"><Header /><main>
    <section className="relative overflow-hidden bg-navy-950 py-24 text-white md:py-32"><div className="absolute inset-0 blueprint-grid opacity-35" /><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><span className="text-[10px] font-extrabold uppercase tracking-[.22em] text-orange-400">Digital engineering</span><h1 className="mt-4 max-w-4xl font-display text-4xl font-extrabold sm:text-6xl">{pageContent.heroTitle || "Technology that makes engineering clearer."}</h1><p className="mt-6 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">The strongest engineering organizations use digital tools to improve coordination, information flow and decision quality—not to replace engineering judgement.</p></div></section>
    <section className="py-20 md:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{digitalCapabilities.map((item, i) => { const Icon=item.icon; return <article key={item.title} className="rounded-3xl border border-slate-200 bg-slate-50 p-7 transition hover:-translate-y-1 hover:bg-white hover:shadow-xl"><div className="flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-navy-950 text-orange-400"><Icon className="h-5 w-5" /></span><span className="font-mono-tag text-[10px] text-slate-400">TECH / 0{i+1}</span></div><h2 className="mt-7 font-display text-lg font-extrabold text-wix-dark">{item.title}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{item.description}</p></article>; })}</div><div className="mt-12 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border border-slate-200 p-6"><p className="text-[10px] font-extrabold uppercase tracking-widest text-orange-600">BIM</p><h3 className="mt-2 font-display text-lg font-extrabold">Model before conflict becomes site rework.</h3><p className="mt-2 text-xs leading-6 text-slate-500">Use coordinated models and structured review where they make interdisciplinary interfaces easier to see.</p></div><div className="rounded-2xl border border-slate-200 p-6"><p className="text-[10px] font-extrabold uppercase tracking-widest text-orange-600">DATA</p><h3 className="mt-2 font-display text-lg font-extrabold">Turn project information into decisions.</h3><p className="mt-2 text-xs leading-6 text-slate-500">Keep quantities, revisions, drawings and project status organized so the team can work from the same context.</p></div><div className="rounded-2xl border border-slate-200 p-6"><p className="text-[10px] font-extrabold uppercase tracking-widest text-orange-600">DIGITAL DELIVERY</p><h3 className="mt-2 font-display text-lg font-extrabold">Make technical output easier to use.</h3><p className="mt-2 text-xs leading-6 text-slate-500">The end product is not the software model. It is a better engineering decision and a cleaner deliverable.</p></div></div><Link href="/project-planner" className="mt-10 inline-flex items-center gap-2 rounded-full bg-navy-950 px-6 py-3 text-xs font-extrabold uppercase tracking-widest text-white hover:bg-orange-500">Discuss a digital workflow <ArrowRight className="h-4 w-4" /></Link></div></section>
  {pageContent.contentHtml && <section className="prose prose-slate mx-auto max-w-4xl px-4 pb-16 sm:px-6 lg:px-8" dangerouslySetInnerHTML={{__html: pageContent.contentHtml}} />}
  </main><Footer /></div>;
}
